/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export enum UserStatus {
  ACTIVE = 'active',
  SUSPENDED = 'suspended',
  EXPIRED = 'expired',
}

export enum SystemUserRole {
  ADMIN = 'admin',
  GUARD = 'guard', // Left for potential backwards-compatibility, but Resident is now primary
  SUPERVISOR = 'supervisor',
  AUDITOR = 'auditor',
  RESIDENTE = 'residente',
}

export enum LogType {
  CHECK_IN = 'check-in',
  CHECK_OUT = 'check-out',
}

export enum LogStatus {
  SUCCESS = 'success',
  REVOKED_USER = 'revoked_user',
  OUTSIDE_SCHEDULE = 'outside_schedule',
  ALREADY_USED = 'already_used',
  EXPIRED_TOKEN = 'expired_token',
}

export interface AuthorizedUser {
  id: string;
  name: string;
  documentId: string;
  email: string;
  phone: string;
  status: UserStatus;
  qrcodeToken: string;
  oneTime: boolean;
  used: boolean;
  validFrom: string; // ISO DateTime
  validUntil: string; // ISO DateTime
  days: number[]; // e.g [1, 2, 3, 4, 5] (1=Mon, ..., 7=Sun or 0=Sun depending on date implementation, we will use standard: 0=Sunday, 1=Monday... 6=Saturday)
  startTime: string; // "08:00"
  endTime: string; // "18:00"
  createdAt: string; // ISO DateTime
  updatedAt: string; // ISO DateTime
  createdBy: string; // Admin UID or Resident UID
  residenciaId?: string; // Target residence ID
  residenciaNombre?: string; // Target residence name
  isResidentCreated?: boolean; // Flag to indicate if this invitation was generated by a resident
  residentName?: string; // Name of the resident who registered this visit
  residentPhone?: string; // Contact phone of the resident registering this visit
}

export interface AccessLog {
  id: string;
  userId: string;
  userName: string;
  documentId: string;
  timestamp: string; // ISO DateTime
  type: LogType;
  status: LogStatus;
  guardId: string;
  guardName: string;
  residenciaId?: string;
  residenciaNombre?: string;
  casetaId?: string;
  casetaNombre?: string;
}

export interface SystemRole {
  uid: string;
  email: string;
  name: string;
  role: SystemUserRole;
  createdAt: string; // ISO DateTime
  phone?: string;
  password?: string;
  isActive?: boolean;
  residenciaId?: string | null;
  residenciaNombre?: string | null;
  casetaId?: string | null;
  casetaNombre?: string | null;
  username?: string;
  avatar?: string;
}

export interface Residencia {
  id: string;
  nombre: string;
  administrador: string;
  numResidencias: number;
  isActive: boolean;
  createdAt: string; // ISO DateTime
  updatedAt: string; // ISO DateTime
  panicActive?: boolean; // Real-time panico sync across admins & guards
}

export interface Residente {
  id: string;
  nombre: string;
  residenciaId: string;
  residenciaNombre: string;
  direccion: string;
  qrcodeToken: string;
  whatsapp?: string; // Optional WhatsApp phone number
  accessUserId?: string; // Optional linked AuthorizedUser id
  validUntil?: string; // Optional validity duration datetime
  createdAt: string; // ISO DateTime
  updatedAt: string; // ISO DateTime
}

export interface Caseta {
  id: string;
  nombre: string;
  residenciaId: string;
  residenciaNombre: string;
  isActive: boolean;
  createdAt: string; // ISO DateTime
  updatedAt: string; // ISO DateTime
}

export interface Marbete {
  id: string;
  consecutivo: number;
  residenteId: string;
  residenteNombre: string;
  residenciaId: string;
  residenciaNombre: string;
  vehiculoPlacas?: string;
  vehiculoInfo?: string; // e.g. "Sentra Gris 2022"
  qrcodeToken: string;
  validFrom: string; // ISO DateTime
  validUntil: string; // ISO DateTime
  status: UserStatus;
  createdAt: string; // ISO DateTime
  updatedAt: string; // ISO DateTime
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
  };
}
